### ISSUE TITLE
Display status title next to number

### ISSUE THREAD

**Issue by eaigner** [citricsquid/httpstatus.es#20]
I think it's very annoying to either have to hover over the code or click it to discover what it actually stands for (what it's official name is).

Couldn't this just be displayed next to the code like this?

    307: TEMPORARY REDIRECT

**Comment by citricsquid** [comment]
You're absolutely right, it makes far more sense to display the official titles instead of a self-written summary, especially given that the titles communicate the meaning of the status code very well. There is a new version of the website to be deployed in the coming days that uses the status code title and doesn't include any self-written summary. 

Sorry about the turnaround time on this, the project had been abandoned for a while, but it's active again. Thanks for taking the time to provide feedback.

**Comment by eaigner** [comment]
Great!
